spring.application.name=JournalEntryApp
spring.config.import=optional:file:./dbProperties/config.properties
spring.data.mongodb.auto-index-creation=true
spring.security.user.name=user
spring.security.user.password=pass
logging.level.org.springframework.security=DEBUG
app.jwt.secret=M3p0YTVzN2Q5Z2g0ajFrM2w0bTVuNnA3cjhzOXR1djE=
spring.profiles.active=dev
